language: python
python:
  - "2.6"
install:
  - "pip install --allow-all-external -r requirements.txt"
  - "sudo apt-get install -y npm"
  - "sudo npm install -g js-yaml"
script: |
  cd playbooks/edx-east
  ansible-playbook -i localhost, --syntax-check edxapp.yml
  js-yaml -c edxapp.yml
