language: python
python:
  - "2.6"
install:
  - "pip install --allow-all-external -r requirements.txt"
script:
  - |
    cd playbooks/edx-east
    for play in *.yml; do
      if ! grep -q "vars_prompt" $play; then
        ansible-playbook -i localhost, --syntax-check --list-tasks $play
      fi
    done
